### ISSUE TITLE
how to get destination ip and url from dns packet ?

### ISSUE THREAD

**Issue by laithabbas** [kaitoy/pcap4j#182]
I have pcap file and i want to know destination ip and url from dns packet ,
i try this to get Ethernet
EthernetPacket eth = EthernetPacket.newPacket(pkt.getRawData(), 0,14);
but i face problem when i run this 
IpV4Packet ipPkt = IpV4Packet.newPacket(pkt.getRawData(), 14, 20);
the output is:

[Ethernet Header (14 bytes)]
  Destination address: f2:3c:17:e1:42:77
  Source address: e4:8d:8c:0a:51:58
  Type: 0x0800 (IPv4)

Exception in thread "main" java.lang.IllegalArgumentException: targetClass: interface org.pcap4j.packet.IpV4Packet$IpV4Tos numberClass: class org.pcap4j.packet.namednumber.NotApplicable
	at org.pcap4j.packet.factory.SimplePacketFactoryBinder.getPacketFactory(SimplePacketFactoryBinder.java:35)
	at org.pcap4j.packet.factory.PacketFactories.getFactory(PacketFactories.java:61)
	at org.pcap4j.packet.IpV4Packet$IpV4Header.<init>(IpV4Packet.java:515)
	at org.pcap4j.packet.IpV4Packet$IpV4Header.<init>(IpV4Packet.java:404)
	at org.pcap4j.packet.IpV4Packet.<init>(IpV4Packet.java:65)
	at org.pcap4j.packet.IpV4Packet.newPacket(IpV4Packet.java:61)
	at com.github.username.App.main(App.java:119)

**Comment by kaitoy** [comment]
You can get a dest ip address by packet.get(IpV4Packet.class).getHeader().getDstAddr().
