### ISSUE TITLE
sample Loop.java fails with "java.lang.UnsupportedOperationException: This code is never included in pcap4j-core.jar."

### ISSUE THREAD

**Issue by jdrews** [kaitoy/pcap4j#19]
I'm getting the following error when attempting to run Loop.java with the latest commit (f888f26). 

java.lang.UnsupportedOperationException: This code is never included in pcap4j-core.jar.

I've encountered this problem when running on Windows 8 (WinPcap 4.1.3) and Ubuntu (libpcap 1.3.0). "mvn install" completes successfully. Below is a capture of when it happens. I redacted mac addresses. 

```
root@jd3560:/media/jdrews/SSD OS/git/pcap4j# java -cp /media/jdrews/SSD\ OS/git/pcap4j/pcap4j-sample/target/classes:/media/jdrews/SSD\ OS/git/pcap4j/pcap4j-core/target/classes:/root/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar:/root/.m2/repository/org/slf4j/slf4j-api/1.6.4/slf4j-api-1.6.4.jar org.pcap4j.sample.Loop
org.pcap4j.sample.Loop.count: 5
org.pcap4j.sample.Loop.readTimeout: 10
org.pcap4j.sample.Loop.snaplen: 65536


SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
NIF[0]: eth0
      : link layer address: xx:xx:xx:xx:xx:xx
NIF[1]: nflog
      : description: Linux netfilter log (NFLOG) interface
NIF[2]: nfqueue
      : description: Linux netfilter queue (NFQUEUE) interface
NIF[3]: eth1
      : link layer address: xx:xx:xx:xx:xx:xx
      : address: /192.168.3.35
      : address: /fe80:0:0:0:c218:85ff:fec4:6dff
NIF[4]: any
      : description: Pseudo-device that captures on all interfaces
NIF[5]: lo
      : link layer address: 00:00:00:00:00:00
      : address: /127.0.0.1
      : address: /0:0:0:0:0:0:0:1

Select a device number to capture packets, or enter 'q' to quit > 3
eth1(null)
JNA: Callback org.pcap4j.core.PcapHandle$GotPacketFuncExecutor@55015495 threw the following exception:
java.lang.UnsupportedOperationException: This code is never included in pcap4j-core.jar.
    at org.pcap4j.packet.factory.PacketFactoryBinder.getPacketFactory(PacketFactoryBinder.java:27)
    at org.pcap4j.packet.factory.PacketFactories.getFactory(PacketFactories.java:56)
    at org.pcap4j.core.PcapHandle$GotPacketFuncExecutor$1.run(PcapHandle.java:815)
    at org.pcap4j.core.PcapHandle$SimpleExecutor.execute(PcapHandle.java:783)
    at org.pcap4j.core.PcapHandle$GotPacketFuncExecutor.got_packet(PcapHandle.java:810)
    at org.pcap4j.core.NativeMappings.pcap_loop(Native Method)
    at org.pcap4j.core.PcapHandle.loop(PcapHandle.java:671)
    at org.pcap4j.core.PcapHandle.loop(PcapHandle.java:634)
    at org.pcap4j.sample.Loop.main(Loop.java:79)
JNA: Callback org.pcap4j.core.PcapHandle$GotPacketFuncExecutor@55015495 threw the following exception:
java.lang.UnsupportedOperationException: This code is never included in pcap4j-core.jar.
    at org.pcap4j.packet.factory.PacketFactoryBinder.getPacketFactory(PacketFactoryBinder.java:27)
    at org.pcap4j.packet.factory.PacketFactories.getFactory(PacketFactories.java:56)
    at org.pcap4j.core.PcapHandle$GotPacketFuncExecutor$1.run(PcapHandle.java:815)
    at org.pcap4j.core.PcapHandle$SimpleExecutor.execute(PcapHandle.java:783)
    at org.pcap4j.core.PcapHandle$GotPacketFuncExecutor.got_packet(PcapHandle.java:810)
    at org.pcap4j.core.NativeMappings.pcap_loop(Native Method)
    at org.pcap4j.core.PcapHandle.loop(PcapHandle.java:671)
    at org.pcap4j.core.PcapHandle.loop(PcapHandle.java:634)
    at org.pcap4j.sample.Loop.main(Loop.java:79)
JNA: Callback org.pcap4j.core.PcapHandle$GotPacketFuncExecutor@55015495 threw the following exception:
java.lang.UnsupportedOperationException: This code is never included in pcap4j-core.jar.
    at org.pcap4j.packet.factory.PacketFactoryBinder.getPacketFactory(PacketFactoryBinder.java:27)
    at org.pcap4j.packet.factory.PacketFactories.getFactory(PacketFactories.java:56)
    at org.pcap4j.core.PcapHandle$GotPacketFuncExecutor$1.run(PcapHandle.java:815)
    at org.pcap4j.core.PcapHandle$SimpleExecutor.execute(PcapHandle.java:783)
    at org.pcap4j.core.PcapHandle$GotPacketFuncExecutor.got_packet(PcapHandle.java:810)
    at org.pcap4j.core.NativeMappings.pcap_loop(Native Method)
    at org.pcap4j.core.PcapHandle.loop(PcapHandle.java:671)
    at org.pcap4j.core.PcapHandle.loop(PcapHandle.java:634)
    at org.pcap4j.sample.Loop.main(Loop.java:79)
JNA: Callback org.pcap4j.core.PcapHandle$GotPacketFuncExecutor@55015495 threw the following exception:
java.lang.UnsupportedOperationException: This code is never included in pcap4j-core.jar.
    at org.pcap4j.packet.factory.PacketFactoryBinder.getPacketFactory(PacketFactoryBinder.java:27)
    at org.pcap4j.packet.factory.PacketFactories.getFactory(PacketFactories.java:56)
    at org.pcap4j.core.PcapHandle$GotPacketFuncExecutor$1.run(PcapHandle.java:815)
    at org.pcap4j.core.PcapHandle$SimpleExecutor.execute(PcapHandle.java:783)
    at org.pcap4j.core.PcapHandle$GotPacketFuncExecutor.got_packet(PcapHandle.java:810)
    at org.pcap4j.core.NativeMappings.pcap_loop(Native Method)
    at org.pcap4j.core.PcapHandle.loop(PcapHandle.java:671)
    at org.pcap4j.core.PcapHandle.loop(PcapHandle.java:634)
    at org.pcap4j.sample.Loop.main(Loop.java:79)
JNA: Callback org.pcap4j.core.PcapHandle$GotPacketFuncExecutor@55015495 threw the following exception:
java.lang.UnsupportedOperationException: This code is never included in pcap4j-core.jar.
    at org.pcap4j.packet.factory.PacketFactoryBinder.getPacketFactory(PacketFactoryBinder.java:27)
    at org.pcap4j.packet.factory.PacketFactories.getFactory(PacketFactories.java:56)
    at org.pcap4j.core.PcapHandle$GotPacketFuncExecutor$1.run(PcapHandle.java:815)
    at org.pcap4j.core.PcapHandle$SimpleExecutor.execute(PcapHandle.java:783)
    at org.pcap4j.core.PcapHandle$GotPacketFuncExecutor.got_packet(PcapHandle.java:810)
    at org.pcap4j.core.NativeMappings.pcap_loop(Native Method)
    at org.pcap4j.core.PcapHandle.loop(PcapHandle.java:671)
    at org.pcap4j.core.PcapHandle.loop(PcapHandle.java:634)
    at org.pcap4j.sample.Loop.main(Loop.java:79)
ps_recv: 6
ps_drop: 0
ps_ifdrop: 0
root@jd3560:/media/jdrews/SSD OS/git/pcap4j#
```

**Comment by chaudharisuresh997** [comment]
does not work out for me

**Comment by kaitoy** [comment]
What did you do and what happened?

**Comment by chaudharisuresh997** [comment]
wanted to test sample programs imported all project in eclipse tried clean
install then tried to execute loop file.

**Comment by kaitoy** [comment]
Did you add pcap4j-packetfactory-static project to your classpath? What happend?

**Comment by sefiroths** [comment]
hi, same problem, I attach an image:
<img width="1262" alt="schermata 2018-11-12 alle 20 48 10" src="https://user-images.githubusercontent.com/1541145/48371531-6bb40480-e6bc-11e8-92ec-9783648d0c82.png">

**Comment by kaitoy** [comment]
Could you paste the entire message of the error?
