### ISSUE TITLE
NullPointerException in DnsDomainName#toString(byte[])

### ISSUE THREAD

**Issue by camsteffen** [kaitoy/pcap4j#200]
I ran into the following NPE. I included the critical portion of the stack trace with line numbers adjusted for 1.7.4.

```
java.lang.NullPointerException: headerRawData is null.
	at org.pcap4j.packet.DnsDomainName.decompress(DnsDomainName.java:255)
	at org.pcap4j.packet.DnsDomainName.toString(DnsDomainName.java:374)
	at org.pcap4j.packet.DnsRDataSoa.convertToString(DnsRDataSoa.java:318)
	at org.pcap4j.packet.DnsRDataSoa.toString(DnsRDataSoa.java:300)
```
This came about by using `DnsResourceRecord#toString()`. Should I prefer `DnsResourceRecord#toString(String indent, byte[] headerRawData)` maybe?

**Comment by kaitoy** [comment]
It looks a bug.
Thank you for your reporting. I will fix it.

**Comment by kaitoy** [comment]
The new version 1.7.5 and 2.0.0-alpha.2 are released with the fix for this issue.
