### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Unable to load library 'wpcap':

### ISSUE THREAD

**Issue by TheCardinalSystem** [kaitoy/pcap4j#203]
I am getting an error when invoking Pcaps.getDevByAddress(). I believe it wants me to install a pcap native library, but I already installed [Npcap](https://nmap.org/npcap/).
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'wpcap':
The specified module could not be found.

The specified module could not be found.

The specified module could not be found.

Native library (win32-x86-64/wpcap.dll) not found in resource path ([file:/C:/Program%20Files/Java/jre1.8.0_201/lib/resources.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/rt.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/jsse.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/jce.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/charsets.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/jfr.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/access-bridge-64.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/cldrdata.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/dnsns.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/jaccess.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/jfxrt.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/localedata.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/nashorn.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/sunec.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/sunjce_provider.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/sunmscapi.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/sunpkcs11.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/zipfs.jar, file:/C:/Users/Cardinal%20System/Eclipse%20Workspace/Stackoverflow/bin/, file:/C:/Users/Cardinal%20System/Eclipse%20Workspace/Libs/Jsoup/jsoup-1.11.3.jar, file:/C:/Users/Cardinal%20System/Eclipse%20Workspace/Libs/Gson/gson-2.8.5.jar, file:/C:/Users/Cardinal%20System/Eclipse%20Workspace/Libs/Pcap4J/pcap4j-core-1.7.5.jar, file:/C:/Users/Cardinal%20System/Eclipse%20Workspace/Libs/Pcap4J/pcap4j-packetfactory-static-1.7.5.jar, file:/C:/Users/Cardinal%20System/Eclipse%20Workspace/Libs/JNA/jna-5.2.0.jar, file:/C:/Users/Cardinal%20System/Eclipse%20Workspace/Libs/JNA/jna-platform-5.2.0.jar, file:/C:/Users/Cardinal%20System/Eclipse%20Workspace/LOTH/Libs/slf4j-api-1.7.25.jar, file:/C:/Users/Cardinal%20System/Eclipse%20Workspace/LOTH/Libs/slf4j-simple-1.7.25.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:397)
	at com.sun.jna.Function.getFunction(Function.java:101)
	at org.pcap4j.core.NativeMappings.<clinit>(NativeMappings.java:44)
	at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:53)
	at org.pcap4j.core.Pcaps.getDevByAddress(Pcaps.java:96)
	at TestClass.main(TestClass.java:34)
	Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 7 more
	Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 7 more
	Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:265)
		... 7 more
	Suppressed: java.io.IOException: Native library (win32-x86-64/wpcap.dll) not found in resource path ([file:/C:/Program%20Files/Java/jre1.8.0_201/lib/resources.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/rt.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/jsse.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/jce.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/charsets.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/jfr.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/access-bridge-64.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/cldrdata.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/dnsns.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/jaccess.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/jfxrt.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/localedata.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/nashorn.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/sunec.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/sunjce_provider.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/sunmscapi.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/sunpkcs11.jar, file:/C:/Program%20Files/Java/jre1.8.0_201/lib/ext/zipfs.jar, file:/C:/Users/Cardinal%20System/Eclipse%20Workspace/Stackoverflow/bin/, file:/C:/Users/Cardinal%20System/Eclipse%20Workspace/Libs/Jsoup/jsoup-1.11.3.jar, file:/C:/Users/Cardinal%20System/Eclipse%20Workspace/Libs/Gson/gson-2.8.5.jar, file:/C:/Users/Cardinal%20System/Eclipse%20Workspace/Libs/Pcap4J/pcap4j-core-1.7.5.jar, file:/C:/Users/Cardinal%20System/Eclipse%20Workspace/Libs/Pcap4J/pcap4j-packetfactory-static-1.7.5.jar, file:/C:/Users/Cardinal%20System/Eclipse%20Workspace/Libs/JNA/jna-5.2.0.jar, file:/C:/Users/Cardinal%20System/Eclipse%20Workspace/Libs/JNA/jna-platform-5.2.0.jar, file:/C:/Users/Cardinal%20System/Eclipse%20Workspace/LOTH/Libs/slf4j-api-1.7.25.jar, file:/C:/Users/Cardinal%20System/Eclipse%20Workspace/LOTH/Libs/slf4j-simple-1.7.25.jar])
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1089)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
		... 7 more

```

**Comment by TheCardinalSystem** [comment]
I found the solution:
```Java
		String prop = System.getProperty("jna.library.path");
		if (prop == null || prop.isEmpty()) {
			prop = "C:/Windows/System32/Npcap";
		} else {
			prop += ";C:/Windows/System32/Npcap";
		}
		System.setProperty("jna.library.path", prop);
```

**Comment by ohuseyinoglu** [comment]
This is documented in the README.md of the project at "How to use/About native library loading/[WinPcap or Npcap](https://github.com/kaitoy/pcap4j#winpcap-or-npcap)" section. You can also check other (more generic) alternatives there.

**Comment by kaitoy** [comment]
@ohuseyinoglu 

Thank you for pointing it out.
