### ISSUE TITLE
ClassCastException: java.net.Inet4Address cannot be cast to java.net.Inet6Address when converting ipv6 mapped ipv4 address parsing

### ISSUE THREAD

**Issue by sanoymathew** [kaitoy/pcap4j#214]
Could you please look at this issue?

It appears like when the library  receives the IPV6 packet that contains IPV6 mapped IPV4 address throws ClassCastException

As far as I know, InetAddress.getByAddress(byte[]) can return Inet4Address type even though it is of 16 bytes length.

java.lang.IllegalArgumentException: java.lang.reflect.InvocationTargetException
        at org.pcap4j.packet.factory.PropertiesBasedPacketFactory.newInstance(PropertiesBasedPacketFactory.java:77)
        at org.pcap4j.packet.factory.PropertiesBasedPacketFactory.newInstance(PropertiesBasedPacketFactory.java:35)
        at org.pcap4j.packet.factory.PropertiesBasedPacketFactory.newInstance(PropertiesBasedPacketFactory.java:21)
        at org.pcap4j.core.PcapHandle$GotPacketFuncExecutor$1.run(PcapHandle.java:1332)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.pcap4j.packet.factory.PropertiesBasedPacketFactory.newInstance(PropertiesBasedPacketFactory.java:64)
        ... 6 more
Caused by: java.lang.IllegalArgumentException: java.lang.reflect.InvocationTargetException
        at org.pcap4j.packet.factory.PropertiesBasedPacketFactory.newInstance(PropertiesBasedPacketFactory.java:77)
        at org.pcap4j.packet.factory.PropertiesBasedPacketFactory.newInstance(PropertiesBasedPacketFactory.java:35)
        at org.pcap4j.packet.factory.PropertiesBasedPacketFactory.newInstance(PropertiesBasedPacketFactory.java:21)
        at org.pcap4j.packet.EthernetPacket.<init>(EthernetPacket.java:89)
        at org.pcap4j.packet.EthernetPacket.newPacket(EthernetPacket.java:55)
        ... 10 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor165.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.pcap4j.packet.factory.PropertiesBasedPacketFactory.newInstance(PropertiesBasedPacketFactory.java:64)
        ... 14 more
Caused by: java.lang.ClassCastException: java.net.Inet4Address cannot be cast to java.net.Inet6Address
        at org.pcap4j.util.ByteArrays.getInet6Address(ByteArrays.java:703)
        at org.pcap4j.util.ByteArrays.getInet6Address(ByteArrays.java:681)
        at org.pcap4j.packet.IpV6Packet$IpV6Header.<init>(IpV6Packet.java:367)
        at org.pcap4j.packet.IpV6Packet$IpV6Header.<init>(IpV6Packet.java:281)
        at org.pcap4j.packet.IpV6Packet.<init>(IpV6Packet.java:56)
        at org.pcap4j.packet.IpV6Packet.newPacket(IpV6Packet.java:52)
        ... 18 more

**Comment by kaitoy** [comment]
Thank you for your  bug report.
I made a commit to fix it.

**Comment by sanoymathew** [comment]
Thank you very much. Are you planning to release  a new version with this fix?

**Comment by kaitoy** [comment]
Yes, it would be soon.
This weekend or so.
