### ISSUE TITLE
Crash reports on 2.0.0-alpha.4

### ISSUE THREAD

**Issue by eakteam** [kaitoy/pcap4j#225]
Hi everything seems to works fine in `2.0.0-alpha.3`, but after update dependencies to `2.0.0-alpha.4` i get some crashes about : 

```
Fatal Exception: java.lang.ExceptionInInitializerError
       at org.pcap4j.packet.factory.PacketFactories.getFactory(PacketFactories.java:67)
       at org.pcap4j.packet.IpSelector.newPacket(IpSelector.java:42)
       at java.lang.Thread.run(Thread.java:764)
```

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.CodeSource java.security.ProtectionDomain.getCodeSource()' on a null object reference
       at org.pcap4j.packet.factory.PacketFactories.<clinit>(PacketFactories.java:40)
       at org.pcap4j.packet.factory.PacketFactories.getFactory(PacketFactories.java:67)
       at org.pcap4j.packet.IpSelector.newPacket(IpSelector.java:42)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by kaitoy** [comment]
Which version of Java did you use and how did you run Pcap4j?

**Comment by eakteam** [comment]
I am using this lib in Android, compiled with JAVA 1.8, but as i said everything works fine on `alpha.3`, the crash happen only in `alpha.4`
Added too in my `R8/Proguard` files rule : `-keep,allowoptimization class org.pcap4j.**`
But it crashes in `Debug & Release` build too no matter for code shrinking

**Comment by kaitoy** [comment]
I found `getProtectionDomain` is not implemented in Android's Java.
https://stackoverflow.com/questions/27790348/getclass-getprotectiondomain-getcodesource-getlocation-getpath-throw-a?rq=1

I will make a fix for this issue.

**Comment by eakteam** [comment]
Thank you for your support ! Will wait for next alpha release to try out. Thanks again

**Comment by kaitoy** [comment]
2.0.0-alpha.5 has been released with the fix.

**Comment by eakteam** [comment]
@kaitoy , thank you !!! Really thank you !
