### ISSUE TITLE
Can't select network interface device 

### ISSUE THREAD

**Issue by phenominal24** [kaitoy/pcap4j#234]
I am working in intelliJ using Maven to add the pcap4j dependency. I have been following the tutorial by Dev_Dungeon. I am stuck at the earliest stage of trying to locate a network device so I can start capturing and analysing packet data. 

I am using Mac OS Mojave.

Unfortunately I get one of these two errors. when I build a jar file and run it.

Haroon@Haroons-MacBook-Pro ~/Desktop/hpcap
$ sudo java -jar target/hpcap-1.0.0.jar
Error: Unable to initialize main class com.github.phenominal24.App
Caused by: java.lang.NoClassDefFoundError: org/pcap4j/core/PcapNativeException

or when I run a slightly different piece of code, I get 

Haroon@Haroons-MacBook-Pro ~/Desktop/hpcap
$ sudo java -jar target/hpcap-1.0.0.jar
Password:
Hello World!
Exception in thread "main" java.lang.NoClassDefFoundError: org/pcap4j/util/NifSelector
        at com.github.phenominal24.App.main(App.java:39)
Caused by: java.lang.ClassNotFoundException: org.pcap4j.util.NifSelector
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 1 more

**Comment by kaitoy** [comment]
You need to add all dependencies to your classpath, at least pcap4j-core.jar, pcap4j-packetfactory-static.jar, jna.jar, and slf4j-api.jar.
