### ISSUE TITLE
Problem with tun devices on FreeBSD

### ISSUE THREAD

**Issue by io7m** [kaitoy/pcap4j#46]
If a `tun` device has been opened (by `openvpn`, for example), using `Pcaps.findAllDevs` will result in:

```
Exception in thread "main" java.lang.AssertionError: devName: tun0 pcapAddr.addr.getSaFamily(): 28 saFamily: 28
	at org.pcap4j.core.AbstractPcapAddress.throwAssetion(AbstractPcapAddress.java:80)
	at org.pcap4j.core.AbstractPcapAddress.<init>(AbstractPcapAddress.java:62)
	at org.pcap4j.core.PcapIpV6Address.<init>(PcapIpV6Address.java:22)
	at org.pcap4j.core.PcapIpV6Address.newInstance(PcapIpV6Address.java:26)
	at org.pcap4j.core.PcapNetworkInterface.<init>(PcapNetworkInterface.java:75)
	at org.pcap4j.core.PcapNetworkInterface.newInstance(PcapNetworkInterface.java:130)
	at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:74)
```

The error message seems nonsensical... It's claiming `28 != 28`?

**Comment by kaitoy** [comment]
The code that threw the exception has an error...
I fixed it. Could you please try the following artifact and let me see the error message.

https://oss.sonatype.org/content/repositories/snapshots/org/pcap4j/pcap4j-core/1.6.1-SNAPSHOT/pcap4j-core-1.6.1-20150920.071529-1.jar

**Comment by io7m** [comment]
Hello!

That artifact changes the error message to something more sensible, at least:

```
Exception in thread "main" java.lang.AssertionError: devName: tun0, field: dstaddr, actual saFamily: 117, expected saFamily: 28
	at org.pcap4j.core.AbstractPcapAddress.throwAssetion(AbstractPcapAddress.java:84)
	at org.pcap4j.core.AbstractPcapAddress.<init>(AbstractPcapAddress.java:62)
	at org.pcap4j.core.PcapIpV6Address.<init>(PcapIpV6Address.java:22)
	at org.pcap4j.core.PcapIpV6Address.newInstance(PcapIpV6Address.java:26)
	at org.pcap4j.core.PcapNetworkInterface.<init>(PcapNetworkInterface.java:75)
	at org.pcap4j.core.PcapNetworkInterface.newInstance(PcapNetworkInterface.java:130)
	at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:74)
	at com.io7m.beancounter.Main.main(Main.java:49)
```

It seems that 117 is `AF_VENDOR39` on FreeBSD. I'm guessing this is a private constant allocated to `openvpn`.

**Comment by kaitoy** [comment]
Thanks.
I couldn't figure out how to analyze addresses with the af family 117.
So, I changed AbstractPcapAddress such that it ignores such addresses.
Please try the following module:
https://oss.sonatype.org/content/repositories/snapshots/org/pcap4j/pcap4j-core/1.6.1-SNAPSHOT/pcap4j-core-1.6.1-20150920.165639-2.jar

**Comment by io7m** [comment]
Nice work, that one works correctly. Packet capturing appears to work correctly too!

**Comment by kaitoy** [comment]
Ver 1.6.1 has been released with the fix.
