### ISSUE TITLE
Add support for Android

### ISSUE THREAD

**Issue by kaitoy** [kaitoy/pcap4j#6]

**Comment by kyangc** [comment]
GOGOGO

**Comment by kaitoy** [comment]
Oh. I've forgotten this....

**Comment by chenenyu** [comment]
How is the issue going?

**Comment by kaitoy** [comment]
I'm working on v2 and just waiting for someone's contribution for Android support for now....

**Comment by dinkelroman** [comment]
Hey, how is the development going? Is there an ETA?

**Comment by kaitoy** [comment]
I'm planning to complete v2 development in March 2017. Then I will have time for Android support.
It would take a month, I think.

**Comment by krupalshah** [comment]
I successfully added your library in Android project. I just need to write a Pcap file with ipv4 packets got from VPN . How can I do it?

**Comment by kaitoy** [comment]
Sorry but I'm not yet familiar with Android. It seems [DNS66](https://github.com/julian-klode/dns66) project is using Pcap4J on Android, so could you consult its author?

**Comment by giovx24** [comment]
Can i use this on Android to send ARP packet?

**Comment by kaitoy** [comment]
I have no idea for now.

**Comment by giovx24** [comment]
Ok Thanks

**Comment by elile** [comment]
Trying this library on android, I got:

FATAL EXCEPTION: main
Process: com.play.around, PID: 29329
java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/android-arm/libjnidispatch.so) not found in resource path (.)
 at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:866)
 at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:826)
 at com.sun.jna.Native.<clinit>(Native.java:140)
 at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
 at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:28)
 at com.sun.jna.ptr.PointerByReference.<init>(PointerByReference.java:24)
 at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:48)
 at org.pcap4j.util.NifSelector.selectNetworkInterface(NifSelector.java:38)
 at com.play.around.MainActivity.sendArpRequest(MainActivity.java:73)
 at com.play.around.MainActivity$1.onClick(MainActivity.java:51)
 at android.view.View.performClick(View.java:5204)
 at android.view.View$PerformClick.run(View.java:21153)
 at android.os.Handler.handleCallback(Handler.java:739)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:148)
 at android.app.ActivityThread.main(ActivityThread.java:5417)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by tinyoculus** [comment]
How is the issue going?

**Comment by kaitoy** [comment]
No progress actually...
I need to find someone who can help me.

**Comment by writzx** [comment]
I am not sure why this is happening. I got to the point where all the ".so" library would load properly but after that I get this error:

```
FATAL EXCEPTION: main
Process: com.arik.pubgsnitch, PID: 22527
java.lang.UnsatisfiedLinkError: Error looking up function 'pcap_dump': undefined symbol: pcap_dump
    at com.sun.jna.Function.<init>(Function.java:212)
    at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:541)
    at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:518)
    at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:468)
    at com.sun.jna.Function.getFunction(Function.java:82)
    at org.pcap4j.core.NativeMappings.<clinit>(NativeMappings.java:47)
    at org.pcap4j.core.NativeMappings.pcap_findalldevs(Native Method)
    at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:51)
    ...........
```
However for this I had to custom compile libpcap(1.8.1) from [here](https://github.com/aosp-mirror/platform_external_libpcap)and include it in the project.


Is it that using libpcap 1.1.1 will fix this issue? or is this a entirely different problem?

**Comment by writzx** [comment]
I am not sure why this is happening. I got to the point where all the ".so" library would load properly but after that I get this error:

```
FATAL EXCEPTION: main
java.lang.UnsatisfiedLinkError: Error looking up function 'pcap_dump': undefined symbol: pcap_dump
    at com.sun.jna.Function.<init>(Function.java:212)
    at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:541)
    at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:518)
    at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:468)
    at com.sun.jna.Function.getFunction(Function.java:82)
    at org.pcap4j.core.NativeMappings.<clinit>(NativeMappings.java:47)
    at org.pcap4j.core.NativeMappings.pcap_findalldevs(Native Method)
    at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:51)
    ...........
```
However for this I had to custom compile libpcap(1.8.1) from [here](https://github.com/aosp-mirror/platform_external_libpcap) and include it in the project.


Is it that using libpcap 1.1.1 will fix this issue? or is this a entirely different problem?


I also tried to look at the DNS66 project. Didn't find anything special to make pcap4j work. :(

**Comment by writzx** [comment]
UPDATE: I got around the error that I was getting a while ago, and it was because of wrong config for building libpcap. I used the 1.3.0 version from [here](https://github.com/enukane/android-pcap).

After compiling successfully, I found another problem. pcap4j can't find any interface in the device. Pcaps.findAllDevs() returns 0 length list. NifSelector().selectNetworkInterface() returns null. Most probably this is because of root access blocking the scan and root in android is only available via shell. however the project https://github.com/enukane/android-pcap also uses libpcap to capture network packets in a different way maybe. I wonder if its possible to do the same in pcap4j.

**Comment by kaitoy** [comment]
I think so, too. libpcap needs root privileges.

**Comment by writzx** [comment]
However, I noticed that tcpdump successfully and correctly runs and dumps all the packet information. The reason is most likely it can get root permission as its a native executable. That makes the only way to sniff on Android is using a native executable with a shell wrapper around it.

**Comment by Itay2805** [comment]
the main problem from what I can see is that you can't really have the app itself run in a root context (you can only open a root shell and run native programs from there). I was able to get it to work by re implementing the NativeMappings so instead of loading libpcap into the java process, I created a proxy native program that loads the library (and we can run it with root permissions from a shell) and using some dumb ipc (basically just using stdio) it will talk with the java program that will do all the calls. 

I have not tested it with sending packets but I can get all the interfaces (even tho I am getting alot of not supported address families) and I can receive packets so it looks promising.

for the code of the [native program](https://github.com/Itay2805/packet-manipulator/blob/master/app/src/main/cpp/pcapproxy/pcap-proxy.c) and for the code of the [java side](https://github.com/Itay2805/packet-manipulator/blob/master/app/src/main/java/me/itay/pcapproxy/PcapProxy.java)

**Comment by romantictree** [comment]
Sir,How is it going?I want to get some Information in LAN. I find it is available for Windows and Linux,But it is not useful when I play on the Android. Do you have any suggestions?
