### ISSUE TITLE
Parse the UDP payload

### ISSUE THREAD

**Issue by WhiteFangBuck** [kaitoy/pcap4j#98]
Hello @kaitoy ,

I am trying to parse the UDP payload. After passing in the UDP payload we get the following:

dnsPacket = DnsPacket.newPacket(ethPacket.getPayload.getRawData, 28, ethPacket.getPayload.getRawData.length-28)
qdCnt = 1
anCnt = 2
nsCnt = 0
arCnt = 2
Print this  flags = -32384
Print this opCode = 0 (Query)
Print this authoratative answer = false
Print this rCode = 0 (No Error)
cursor = 12
Remaining length = 146
In DnQuestions : rawData= [B@1dbcb209
In DnsQuestion : offset=40 length= 146
 In DnsQuestion : questions = QNAME: olimp.us
QTYPE: 1 (A (Host address))
QCLASS: 1 (Internet (IN))

org.pcap4j.packet.IllegalRawDataException: A label must start with 00 or 11. data: 45 00 00 ba 13 7b 40 00 20 11 ad 0b 86 14 00 98 0c a6 06 5b 00 35 46 6d 00 a6 3d 16 03 f0 81 80 00 01 00 02 00 00 00 02 05 6f 6c 69 6d 70 02 75 73 00 00 01 00 01 05 6f 6c 69 6d 70 02 75 73 00 00 01 00 01 00 01 51 80 00 0d 31 33 37 2e 31 32 36 2e 38 2e 32 34 30 05 6f 6c 69 6d 70 02 75 73 00 00 01 00 01 00 01 51 80 00 0d 31 33 37 2e 31 32 36 2e 38 2e 32 34 30 05 6f 6c 69 6d 70 02 75 73 00 00 01 00 01 00 01 51 80 00 0d 31 33 37 2e 31 32 36 2e 38 2e 32 34 30 05 6f 6c 69 6d 70 02 75 73 00 00 01 00 01 00 01 51 80 00 0d 31 33 37 2e 31 32 36 2e 38 2e 32 34 30, offset: 78, length: 108
  at org.pcap4j.packet.DnsDomainName.<init>(DnsDomainName.java:126)
  at org.pcap4j.packet.DnsDomainName.newInstance(DnsDomainName.java:63)
  at org.pcap4j.packet.DnsResourceRecord.<init>(DnsResourceRecord.java:85)
  at org.pcap4j.packet.DnsResourceRecord.newInstance(DnsResourceRecord.java:78)
  at org.pcap4j.packet.DnsPacket$DnsHeader.<init>(DnsPacket.java:496)
  at org.pcap4j.packet.DnsPacket$DnsHeader.<init>(DnsPacket.java:355)
  at org.pcap4j.packet.DnsPacket.<init>(DnsPacket.java:56)
  at org.pcap4j.packet.DnsPacket.newPacket(DnsPacket.java:52)
  ... 68 elided

From the wireshark, I see that that the two answers are parsed correctly. Would there be something that I might be missing here?

**Comment by WhiteFangBuck** [comment]
I think I have an idea what is happening with this particular packet. The answer fields in wireshark, both of them to be of 33 bytes each, but the actual sub fields in there, and the way they are computed in rivate DnsResourceRecord(
    byte[] rawData, int offset, int length
  ) use only the fields Name, Type, Dclass, TTl, data length and address and  which amounts to answer length 24 each. For some reason it is not taking the last 9 bytes.

Would you know how we can factor that in to the code?

The 
<img width="734" alt="screen shot 2017-05-16 at 9 49 11 pm" src="https://cloud.githubusercontent.com/assets/12212918/26136451/bad72e2c-3a81-11e7-8e76-e91a0185dee6.png">

**Comment by WhiteFangBuck** [comment]
Hello!

So I found the issue and have made modifications to the code to handle the packets. I am not sure what is the protocol to add the changes or have the changes vetted by you. Would a pull request do?

Thanks

**Comment by kaitoy** [comment]
Hello.
Thank you for your investigation.
I've found the cause, too. The ADDRESS field of A RDATA is not encoded, but it's a plain text, right?
Wireshark also wrongly parses it.
Could you send a PR?

**Comment by WhiteFangBuck** [comment]
I am not sure about the encoding. It does get the IpV4 address right though.
I will submit the PR.

I see another issue with parsing Inetv6Address. It uses (Inetv6Address)InetAddress.getByAddress(byte[])

But it throws following exception. Would you want me to open this is another issue? Or this might be related to my own data. Would you verify this please?
 java.lang.ClassCastException: java.net.Inet4Address cannot be cast to java.net.Inet6Address
  at org.pcap4j.util.ByteArrays.getInet6Address(ByteArrays.java:748)
  at org.pcap4j.util.ByteArrays.getInet6Address(ByteArrays.java:715)
  at org.pcap4j.packet.DnsRDataAaaa.<init>(DnsRDataAaaa.java:76)
  at org.pcap4j.packet.DnsRDataAaaa.newInstance(DnsRDataAaaa.java:58)
  at org.pcap4j.packet.factory.StaticDnsRDataFactory$17.newInstance(StaticDnsRDataFactory.java:277)
  at org.pcap4j.packet.factory.StaticDnsRDataFactory.newInstance(StaticDnsRDataFactory.java:311)
  at org.pcap4j.packet.factory.StaticDnsRDataFactory.newInstance(StaticDnsRDataFactory.java:40)
  at org.pcap4j.packet.DnsResourceRecord.<init>(DnsResourceRecord.java:144)
  at org.pcap4j.packet.DnsResourceRecord.newInstance(DnsResourceRecord.java:78)
  at org.pcap4j.packet.DnsPacket$DnsHeader.<init>(DnsPacket.java:499)

**Comment by kaitoy** [comment]
`olimp.us` should be resolved to `137.126.8.240` instead of `49.51.55.46`, right?
